# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := game-framework imgui CS488Project

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

game-framework: 
	@echo "==== Building game-framework ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f game-framework.make

imgui: 
	@echo "==== Building imgui ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f imgui.make

CS488Project: game-framework imgui
	@echo "==== Building CS488Project ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f CS488Project.make

clean:
	@${MAKE} --no-print-directory -C build -f game-framework.make clean
	@${MAKE} --no-print-directory -C build -f imgui.make clean
	@${MAKE} --no-print-directory -C build -f CS488Project.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   game-framework"
	@echo "   imgui"
	@echo "   CS488Project"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
